M48
; DRILL file {KiCad 8.0.5-8.0.5-0~ubuntu22.04.1} date 2024-09-10T12:37:44+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-09-10T12:37:44+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5-8.0.5-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X110.0Y-75.0
X110.0Y-133.0
X158.0Y-75.0
X158.0Y-133.0
M30
